version: "3"
services:
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    environment:
      - TZ=Asia/Shanghai
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://127.0.0.1:9200
      - ES_USERNAME=elastic
      - ES_PASSWORD=elastic
      - LOG_LEVEL=debug
    privileged: true
    restart: always
    ports:
      - "16686:16686"
      - "14268:14268"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "4317:4317"
      - "4318:4318"
      - "14250:14250"
      - "14269:14269"
      - "9411:9411"