
version: '2'
services:
  nsqlookupd:
    container_name: nsqlookupd
    image: nsqio/nsq:v1.3.0
    command: /nsqlookupd
    networks:
      - nsq-network
    hostname: nsqlookupd
    ports:
      - "4161:4161"
      - "4160:4160"
  nsqd:
    container_name: nsqd
    image: nsqio/nsq:v1.3.0
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160 -broadcast-address=127.0.0.1
    depends_on:
      - nsqlookupd
    hostname: nsqd
    networks:
      - nsq-network
    ports:
      - "4151:4151"
      - "4150:4150"
  nsqadmin:
    container_name: nsqadmin
    image: nsqio/nsq:v1.3.0
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd
    hostname: nsqadmin
    ports:
      - "4171:4171"
    networks:
      - nsq-network
 
networks:
  nsq-network:
    driver: bridge